import Head from "next/head";

export default function about() {
  return (
    <>
      <Head>
        <title>About - Hack'O'naut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About page</h1>
    </>
  );
}
