import Head from "next/head";

export default function contact() {
  return (
    <>
      <Head>
        <title>Contact - Hack'O'naut </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>contact</h1>
    </>
  );
}
