import Head from "next/head";
export default function registor() {
  return (
    <>
      <Head>
        <title>Register - Hack'O'naut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>registor</h1>
    </>
  );
}
